### ISSUE TITLE
SDK: Throw an error if quote doesn't match the expected price

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#210]
We want to protect users from price changes when they go to buy tokens.

**Solution**

- In the buyToken method, add an optional parameter called `expectedPrice`
- This allows the app to pass the price that they showed to the user (e.g. from tokens API)
- The `execute/buy` API returns a `quote` of how much the transaction will cost
- If `expectedPrice` was passed AND it doesn't match, throw an error
- Also do the same thing when accepting offers

**Comment by ptrwtts** [comment]
Looks good! 

Although I think I just realized an edge-case that we need to handle. 

With dutch auctions, the price is always going down. We cache the price every 5 minutes in the tokens table, which is what is returned in the tokens API. But when you fill, the backend will quote the exact current price, which will be lower than the expectedPrice. In this scenario, the user is getting a better deal than they expected, so would want to proceed.

So I think we need to adjust this so that it only throws an error if the execution is _worse_ for the user.

- When buying, throw error if `quote` > `expectedPrice`
- When selling, throw error if `quote` < `expectedPrice`

@georgeroman is this correct?

**Comment by georgeroman** [comment]
> Looks good!
> 
> Although I think I just realized an edge-case that we need to handle.
> 
> With dutch auctions, the price is always going down. We cache the price every 5 minutes in the tokens table, which is what is returned in the tokens API. But when you fill, the backend will quote the exact current price, which will be lower than the expectedPrice. In this scenario, the user is getting a better deal than they expected, so would want to proceed.
> 
> So I think we need to adjust this so that it only throws an error if the execution is _worse_ for the user.
> 
>     * When buying, throw error if `quote` > `expectedPrice`
> 
>     * When selling, throw error if `quote` < `expectedPrice`
> 
> 
> @georgeroman is this correct?

Yes, that should do it.
