### ISSUE TITLE
Update colors of connect wallet button

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#28]
<img width="525" alt="Screen Shot 2022-02-01 at 12 14 45 PM" src="https://user-images.githubusercontent.com/96800113/152017199-f1da7c5b-ab92-4ba3-a6ab-f7f0ea741757.png">

Purple:
6B4EE2

White:
FFFFFF

**Comment by diegoramosxyz** [comment]
@rorygeoghegan My ui library generates buttons with good contrast ratios, [see calculator](https://webaim.org/resources/contrastchecker/). It uses [tailwindcss colors](https://tailwindcss.com/docs/customizing-colors) such that `btn-{color}-fill-dark` becomes a fully styled button. I changed the button to dark purple. Do you like the way it looks? Otherwise, if you want the sample-marketplace to have custom colors we should have all shades from 50 to 900 like tailwind does.

**Comment by rorygeoghegan** [comment]
I understand. Let's just use black bg and white text for now then.
